# Generated by Django 6.0.5 on 2026-05-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='generated_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
