# Generated by Django 6.0.5 on 2026-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_course_level_coursecontent_coursefile_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Instructor', max_length=150),
        ),
    ]
