# Generated by Django 6.0.5 on 2026-05-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_remove_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('desarrollo-web', 'Desarrollo Web'), ('inteligencia-artificial', 'Inteligencia Artificial'), ('ciencia-de-datos', 'Ciencia de Datos'), ('desarrollo-movil', 'Desarrollo Móvil'), ('diseno-ux-ui', 'Diseño UX/UI'), ('cloud-devops', 'Cloud & DevOps')], max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
