# Generated by Django 6.0.5 on 2026-05-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='enrollment.coursecontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='enrollment.student')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('student', 'content')},
            },
        ),
    ]
