# Generated by Django 6.0.5 on 2026-05-19 21:38

from django.db import migrations

CATEGORY_MAP = {
    'Fundamentos de IA': 'inteligencia-artificial',
    'Machine Learning': 'inteligencia-artificial',
    'Redes Neuronales': 'inteligencia-artificial',
    'Lenguaje Natural (NLP)': 'inteligencia-artificial',
    'Visión Computacional': 'inteligencia-artificial',
    'Proyecto Final': 'inteligencia-artificial',
    'Regresión Lineal': 'ciencia-de-datos',
    'Algoritmo Genético': 'inteligencia-artificial',
}


def assign_categories(apps, schema_editor):
    Course = apps.get_model('enrollment', 'Course')
    for title, category in CATEGORY_MAP.items():
        Course.objects.filter(title=title).update(category=category)


def reverse_categories(apps, schema_editor):
    Course = apps.get_model('enrollment', 'Course')
    Course.objects.filter(category__in=set(CATEGORY_MAP.values())).update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_contentprogress'),
    ]

    operations = [
        migrations.RunPython(assign_categories, reverse_categories),
    ]
